[package]
name = "lucius_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quote = "1"
syn = { version = "2.0.107", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
common = { path = "../common" }
